# Save this file as:  .streamlit/secrets.toml
# (create the .streamlit folder next to your quiz_app.py)

SUPABASE_URL = "https://cvjhgtfvcsiiihhwioua.supabase.co"
SUPABASE_KEY = "sb_publishable_q2FZ3IrLpuGUopT6o-htZA_KyMpxwzn"
